ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - '@swc/core'

packages:
  - apps/*
  - packages/*

catalogs:
  react:
    # react
    'react': '^19.1.0'
    '@types/react': '^19.1.6'
    # react-dom
    'react-dom': '^19.1.0'
    '@types/react-dom': '^19.1.2'
    # react-router-dom
    'react-router-dom': '^7.7.1'

  vite:
    'vite': '^7.0.5'
    '@vitejs/plugin-react-swc': '^3.11.0'

  config:
    '@typescript-eslint/eslint-plugin': '^8.38.0'
    '@typescript-eslint/parser': '^8.38.0'
    'eslint-config-prettier': '^9.1.2'
    'prettier': '^3.6.2'

  typescript:
    'typescript': '5.8.3'

  eslint:
    'eslint': '^9.32.0'
    'eslint-plugin-react-hooks': '^5.2.0'
    'eslint-plugin-react-refresh': '^0.4.20'

  test:
    '@testing-library/user-event': '^14.6.1'
    '@testing-library/dom': '^10.4.1'
    '@testing-library/jest-dom': '^6.6.4'
    '@testing-library/react': '^16.3.0'
    'vitest/ui': '^3.2.4'
    'vitest': '^3.2.4'
    'jsdom': '^26.1.0'

    '@vitest/ui': '^3.2.4'
